# 定义组织机构实体
Organizations:
  - &Order
    Name: Trace # 组织的名称
    ID: TraceMSP # 组织的 MSPID
    MSPDir: crypto-config/ordererOrganizations/trace.com/msp #组织的证书相对位置（生成的crypto-config目录)

  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.com/msp
    AnchorPeers: # 组织锚节点的配置
      - Host: peer0.org1.com
        Port: 7051

  - &Org2
    Name: Org2
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2.com/msp
    AnchorPeers: # 组织锚节点的配置
      - Host: peer0.org2.com
        Port: 7051
  
  - &Org3
    Name: Org3
    ID: Org3MSP
    MSPDir: crypto-config/peerOrganizations/org3.com/msp
    AnchorPeers: # 组织锚节点的配置
      - Host: peer0.org3.com
        Port: 7051

  - &Org4
    Name: Org4
    ID: Org4MSP
    MSPDir: crypto-config/peerOrganizations/org4.com/msp
    AnchorPeers: # 组织锚节点的配置
      - Host: peer0.org4.com
        Port: 7051

  - &Org5
    Name: Org5
    ID: Org5MSP
    MSPDir: crypto-config/peerOrganizations/org5.com/msp
    AnchorPeers: # 组织锚节点的配置
      - Host: peer0.org5.com
        Port: 7051

# 定义了排序服务的相关参数，这些参数将用于创建创世区块
Orderer: &OrdererDefaults
  # 排序节点类型用来指定要启用的排序节点实现，不同的实现对应不同的共识算法
  OrdererType: solo # 共识机制
  Addresses: # Orderer 的域名（用于连接）
    - orderer.trace.com:7050
  BatchTimeout: 2s # 出块时间间隔
  BatchSize: # 用于控制每个block的信息量
    MaxMessageCount: 10 #每个区块的消息个数
    AbsoluteMaxBytes: 99 MB #每个区块最大的信息大小
    PreferredMaxBytes: 512 KB #每个区块包含的一条信息最大长度
  Organizations:

# 定义Peer组织如何与应用程序通道交互的策略
# 默认策略：所有Peer组织都将能够读取数据并将数据写入账本
Application: &ApplicationDefaults
  Organizations:

# 用来定义用于 configtxgen 工具的配置入口
# 将 Profile 参数（ FiveOrgsOrdererGenesis 或 FiveOrgsChannel ）指定为 configtxgen 工具的参数
Profiles:
  #  FiveOrgsOrdererGenesis配置文件用于创建系统通道创世块
  #  该配置文件创建一个名为SampleConsortium的联盟
  #  该联盟在configtx.yaml文件中包含两个Peer组织Taobao和JD
  FiveOrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Order
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
          - *Org2
          - *Org3
          - *Org4
          - *Org5
  # 使用FiveOrgsChannel配置文件创建应用程序通道
  FiveOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5