# 排序节点的组织定义
OrdererOrgs:
  - Name: Trace # 名称
    Domain: trace.com # 域名
    Specs: # 节点域名：orderer.trace.com
      - Hostname: orderer # 主机名

# peer节点的组织定义
PeerOrgs:
  - Name: Org1 # 名称
    Domain: org1.com # 域名
    Template: # 使用模板定义。Count 指的是该组织下组织节点的个数
      Count: 1 # 节点域名：peer0.org1.com 和 peer1.org1.com
    Users: # 组织的用户信息。Count 指该组织中除了 Admin 之外的用户的个数
      Count: 1 # 用户：Admin 和 User1

  - Name: Org2
    Domain: org2.com
    Template:
      Count: 1 
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org4
    Domain: org4.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org5
    Domain: org5.com
    Template:
      Count: 1
    Users:
      Count: 1